eureka:
  client:
    serviceUrl:
      #注册中心的地址
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
mybatis: 
  mapperLocations: classpath*:mybatis-mapper/*/*Mapper.xml
  typeAliasesPackage: cn.edu.imut.**.domain.**.entity.**
spring:
  application:
    #当前应用名称
    name: jm-journal